name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Force Failure
        run: go test -cover ./...

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec test
        run: gosec ./...

      - name: Install sqlc
        uses: sqlc-dev/sqlc-action@v4
        with:
          # This will run 'sqlc generate' automatically
          # and fail the build if the generated code results in a git diff
          backend: "golang"
          directory: "."
      

  format-tester:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"
          
      - name: check formatting
        run: test -z "$(go fmt ./...)"

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: run staticcheck
        run: staticcheck ./... 
